alias ls='ls --color=auto'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias yg='you-get --no-caption'
alias pop='you-get --itag='
alias fla='firewall-cmd --list-all'
alias eth0='ifconfig enp1s0 | grep pack'
alias seek='ssh root@seek.ixixx.ru -p 12222'
alias lll='ls -alh'
alias ll='ls -al'
alias python='python3'
alias pp6='ping6 -n'
alias nu='netstat -anupl'
alias nt='netstat -antpl'
alias tunn='tcpdump -nni tun0 host'
alias scmd='system --reload'
alias screenqq='screen -D -r'
alias screens='screen -ls'
alias fcmd2='firewall-cmd --reload'
alias grepi='grep -i'
alias tcpp='tcpdump -nni any'
alias tun='tcpdump -nni tun0 ! ip6 and host !'
alias yytt='yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a]'
alias yyttt='yt-dlp -o "%(title)s.%(ext)s"'
alias yyttp='yt-dlp -o "%(playlist)s.%(ext)s"'
alias yyttpt='yt-dlp -o "%(playlist)s.%(title)s.%(ext)s"'     
alias llll="ls -l | awk '{print $9}'"
alias cbaliyunpan="aliyunpan ll -name --asc"
